#!/usr/bin/env bash
# Display To infinity and beyond indefinitely each two seconds and have a trap for SIGNALS.

trap "echo \"I am invincible!!!\"" SIGTERM

while true
do
	echo "To infinity and beyond"
	sleep 2
done
